### ISSUE TITLE
Update UI to better fit v1.2 Mockup

### ISSUE THREAD

**Issue by jovantanyk** [AY2324S2-CS2103T-T08-1/tp#26]
Overarching Epic - Refresh and update UI elements to reflect mockup
- [x] Update Main Window #25 
- [ ] Update Command Box #24 
- [x] Update Results Box #23 
- [ ] Update Person Panel #22 
<img width="621" alt="Ui" src="https://github.com/AY2324S2-CS2103T-T08-1/tp/assets/41192630/9920e194-c4f8-4ff2-801b-a9bc6c303267">
