### ISSUE TITLE
Add New Commands in accordance to User Stories

### ISSUE THREAD

**Issue by jovantanyk** [AY2324S2-CS2103T-T08-1/tp#27]
Add New Commands for User Stories
- [x] Read Command #20 
- [x] Create Patient Command #16 
- [x] Find Patient Command #19 
- [x] Delete Patient Command #17 
- [x] Update Information Command #18 
- [x] Update Fields #15
